config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'devise/confirmations' }

  resources :accounts
  resources :budgets
  resources :transactions

  root to: 'home#index'
end

app/models/budget.rb
# frozen_string_literal: true

class Budget < ApplicationRecord
  belongs_to :user
  belongs_to :category

  validates :amount, presence: true
  validates :budget_month, presence: true
  validate :unique_budget_per_month

  def spent_amount
    Transaction.by_category_and_month(user, category_id, budget_month).sum(:amount)
  end

  private

  def unique_budget_per_month
    existing_budget = Budget.find_by(category:, budget_month:, user:)
    return unless existing_budget && existing_budget != self

    errors.add(:base, 'The budget already exists for this category and month. Please edit the existing budget.')
  end
end

app/controllers/budgets_controller.rb
# frozen_string_literal: true

class BudgetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_budget, only: %i[show edit update destroy]
  before_action :set_categories_and_months, only: %i[new create edit update]

  def index
    @budgets = policy_scope(current_user.budgets.includes(:category))
  end

  def show
    authorize @budget
  end

  def new
    @budget = Budget.new
  end

  def create
    @budget = current_user.budgets.build(budget_params)

    if @budget.save
      redirect_to budgets_path, notice: 'Budget was successfully created.'
    elsif @budget.errors[:base].include?('The budget already exists for this category and month. Please edit the existing budget.')
      existing_budget = current_user.budgets.find_by(category_id: budget_params[:category_id],
                                                     budget_month: budget_params[:budget_month])
      redirect_to edit_budget_path(existing_budget),
                  alert: 'The budget already exists for this category and month. Please edit the existing budget.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @budget
  end

  def update
    authorize @budget

    if @budget.update(budget_params)
      redirect_to budgets_path, notice: 'Budget was successfully updated.'
    elsif @budget.errors[:base].include?('The budget already exists for this category and month. Please edit the existing budget.')
      existing_budget = current_user.budgets.find_by(category_id: budget_params[:category_id],
                                                     budget_month: budget_params[:budget_month],
                                                     amount: budget_params[:amount])
      redirect_to edit_budget_path(existing_budget),
                  alert: 'The budget already exists for this category and month. Please edit the existing budget.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @budget
    @budget.destroy
    redirect_to budgets_path, notice: 'Budget was successfully destroyed.'
  end

  private

  def set_budget
    @budget = current_user.budgets.find(params[:id])
  end

  def budget_params
    params.require(:budget).permit(:amount, :category_id, :notes, :budget_month)
  end

  def set_categories_and_months
    @categories = Category.all
    @next_12_months = (0..11).map { |i| Time.now.beginning_of_month + i.months }
  end
end

app/helpers/budgets_helper.rb
# frozen_string_literal: true

module BudgetsHelper
end

app/views/budgets/edit.html.erb
<%= form_with(model: @budget, local: true) do |form| %>
  <% if @budget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@budget.errors.count, "error") %> prohibited this @budget from being saved:</h2>

      <ul>
        <% budget.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, @categories, :id, :name %>
  </div>

  <div class="field">
    <%=form.label :notes%>
    <%= form.text_area :notes%>
  </div>

  <div class="field">
    <%= form.label :budget_month %>
    <%= form.select :budget_month, options_for_select(@next_12_months.map { |date| [date.strftime("%B %Y"), date] }, selected: @budget.budget_month) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/budgets/index.html.erb
<h1>My Budgets</h1>
<%= link_to 'New Budget', new_budget_path %>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Note</th>
      <th>Amount</th>
      <th>Spent</th>
      <th>Period</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @budgets.each do |budget| %>
      <tr>
        <td><%= budget.category.name %></td>
        <td><%= budget.notes%>
        <td><%= budget.amount %></td>
        <td><%= budget.spent_amount %></td>
        <td><%= budget.budget_month.strftime("%B %Y") %></td>
        <td>
          <%= link_to 'Show', budget_path(budget) %>
          <%= link_to 'Edit', edit_budget_path(budget) %>
          <%= button_to 'Delete', budget_path(budget), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/budgets/new.html.erb
<% if alert %>
  <div>
    <%= alert %>
  </div>
<% end %>

<% if notice %>
  <div>
    <%= notice %>
  </div>
<% end %>

<%= form_with(model: @budget, local: true) do |form| %>
  <% if @budget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@budget.errors.count, "error") %> prohibited this @budget from being saved:</h2>

      <ul>
        <% @budget.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, @categories, :id, :name %>
  </div>

  <div class="field">
    <%=form.label :notes%>
    <%= form.text_area :notes%>
  </div>

  <div class="field">
    <%= form.label :budget_month %>
    <%= form.select :budget_month, options_for_select(@next_12_months.map { |date| [date.strftime("%B %Y"), date] }) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/budgets/show.html.erb
<h1>Budget Details</h1>

<p>
  <strong>Amount:</strong>
  <%= @budget.amount %>
</p>

<p>
  <strong>Spent:</strong>
  <%= @budget.spent_amount %>
</p>

<p>
  <strong>Category:</strong>
  <%= @budget.category&.name %>
</p>

<p>
  <strong>Note:</strong>
  <%=@budget.notes%>
</p>

<p>
  <strong>Period:</strong>
  <%= @budget.budget_month.strftime("%B %Y") %>
</p>

<p>
  <strong>Created At:</strong>
  <%= @budget.created_at.strftime('%Y-%m-%d %H:%M') %>
</p>

<%= link_to 'Edit', edit_budget_path(@budget) %> |
<%= link_to 'Back', budgets_path %>