config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'devise/confirmations' }

  resources :accounts
  resources :budgets
  resources :transactions

  root to: 'home#index'
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @accounts = current_user.accounts.order(created_at: :desc).page(params[:page]).per(5)
    @budgets = current_user.budgets.order(created_at: :desc).includes(:category).page(params[:page]).per(5)
    @transactions = current_user.transactions.order(created_at: :desc).page(params[:page]).per(5)
    @categories = Category.all
    # @spent_amounts = @budgets.map(&:spent_amount)
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/home/index.html.erb
<div class="content">
  <div class="column">
    <h2>My Accounts</h2>
    <% if @accounts.present? %>
      <table class="table table-striped mt-4">
        <thead>
          <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Balance</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @accounts.each do |account| %>
            <tr>
              <td><%= account.name %></td>
              <td><%= account.account_type %></td>
              <td><%= account.balance %></td>
              <td>
                <%= link_to 'Show', account_path(account) %>
                <%= link_to 'Edit', edit_account_path(account) %>
                <%= button_to 'Delete', account_path(account), method: :delete, data: { confirm: 'Are you sure?' } %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to "See All Accounts", accounts_path %>
    <% else %>
      <p>No accounts available.</p>
    <% end %>
  </div>

  <div class="column">
    <h2>My Budgets</h2>
    <% if @budgets.present? %>
      <table class="table table-striped mt-4">
        <thead>
          <tr>
            <th>Category</th>
            <th>Notes</th>
            <th>Amount</th>
            <th>Spent</th>
            <th>Period</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
            <% @budgets.each do |budget| %>
              <tr>
                <td><%= budget.category.name %></td>
                <td><%= budget.notes %></td>
                <td><%= budget.amount %></td>
                <td><%= budget.spent_amount %></td>
                <td><%= budget.budget_month.strftime("%B %Y") %></td>
                <td>
                  <%= link_to 'Show', budget_path(budget) %>
                  <%= link_to 'Edit', edit_budget_path(budget) %>
                  <%= button_to 'Delete', budget_path(budget), method: :delete, data: { confirm: 'Are you sure?' } %>
                </td>
              </tr>
            <% end %>
        </tbody>
      </table>
      <%= link_to "See All Budgets", budgets_path %>
    <% else %>
      <p>No budgets available.</p>
    <% end %>
  </div>
</div>

<div class="transactions">
  <h2>My Transactions</h2>
  <% if @transactions.present? %>
  <table class="table table-striped mt-4">
    <thead>
      <tr>
        <th>Type</th>
        <th>Amount</th>
        <th>Source Account</th>
        <th>Destination Account</th>
        <th>Category</th>
        <th>Description</th>
        <th>Location</th>
        <th>Date</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @transactions.each do |transaction| %>
        <tr>
          <td><%= transaction.type.demodulize %></td>
          <td><%= transaction.amount %></td>
          <td>
            <% if transaction.is_a?(Transactions::Expense) || transaction.is_a?(Transactions::Transfer) %>
              <%= transaction.source_account&.name || "Null" %>
            <% else %>
              <%= '-' %>
            <% end %>
          </td>
          <td>
            <% if transaction.is_a?(Transactions::Income) || transaction.is_a?(Transactions::Transfer) %>
              <%= transaction.destination_account&.name || "Null" %>
            <% else %>
              <%= '-' %>
            <% end %>
          </td>
          <td>
            <%if transaction.is_a?(Transactions::Expense)%>
                <%= transaction.category.name %>
            <%else%> 
                <%= "-" %>
            <%end%>
          </td>
          <td><%= transaction.description %></td>
          <td><%= transaction.location %></td>
          <td><%= l(transaction.created_at, format: :short) %></td>
          <td>
            <%= link_to 'Show', transaction_path(transaction) %>
            <%= link_to 'Edit', edit_transaction_path(transaction) %>
            <%= button_to 'Delete', transaction_path(transaction), method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to "See All Transactions", transactions_path %>
  <%else%>
  <p>No Transactions Found</p>
  <%end%>
</div>