config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'devise/confirmations' }

  resources :accounts
  resources :budgets
  resources :transactions

  root to: 'home#index'
end

app/models/account.rb
# frozen_string_literal: true

class Account < ApplicationRecord
  belongs_to :user

  enum account_type: { cash: 'cash', current: 'current', saving: 'saving', investment: 'investment',
                       personal: 'personal' }

  validates :account_type, :balance, presence: true

  def transactions
    Transaction.where(source_account_id: id).or(Transaction.where(destination_account_id: id))
  end
end

app/controllers/accounts_controller.rb
# frozen_string_literal: true

class AccountsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_account, only: %i[show edit update destroy]
  before_action :set_transactions, only: %i[show]

  def index
    @accounts = policy_scope(Account)
  end

  def show
    authorize @account
  end

  def new
    @account = current_user.accounts.new
  end

  def create
    @account = current_user.accounts.build(account_params)

    if @account.save
      redirect_to accounts_path, notice: 'Account was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @account
  end

  def update
    authorize @account

    if @account.update(account_params)
      redirect_to accounts_path, notice: 'Account was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @account

    @account.destroy
    redirect_to root_path, notice: 'Account was successfully deleted.'
  end

  private

  def set_account
    @account = current_user.accounts.find(params[:id])
  end

  def account_params
    params.require(:account).permit(:name, :account_number, :account_type, :balance)
  end

  def set_transactions
    @transactions = @account.transactions.page(params[:page]).per(10)
  end
end

app/helpers/accounts_helper.rb
# frozen_string_literal: true

module AccountsHelper
end

app/views/accounts/_form.html.erb
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
        <% @account.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div>
  <%= form.label :name %>
  <%= form.text_field :name%>
</div>

<div>
  <%= form.label :account_number %>
  <%= form.text_field :account_number%>
</div>

<div>
  <%= form.label :account_type %>
<%= form.select :account_type, options_for_select([['Cash Account', 'cash'], ['Current Account', 'current'], ['Savings Account', 'saving'], ['Investment Account', 'investment'], ['Personal Account', 'personal']]), {} %>
</div>

<div>
  <%= form.label :balance %>
  <%= form.text_field :balance%>
</div>


<div >
  <%= form.submit %>
</div>

app/views/accounts/edit.html.erb
<h1>Edit Account</h1>
<%= form_with(model: @account, url: account_path(@account)) do |form| %>
  <%= render 'form', account: @account, form: form %>
  
<% end %>

<%= link_to 'Back', root_path %>

app/views/accounts/index.html.erb
<h1>My Accounts</h1>
<%= link_to 'New Account', new_account_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>balance</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.name %></td>
        <td><%= account.account_type %></td>
        <td><%= account.balance %></td>
        <td>
          <%= link_to 'Show', account_path(account) %>
          <%= link_to 'Edit', edit_account_path(account), method: :patch %>
          <%= button_to 'Delete', account_path(account), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Home',  root_path%>

app/views/accounts/new.html.erb
<h1>New Account</h1>
<%= form_with(model: @account, url: accounts_path) do |form| %>
<%= render 'form', account: @account, form: form %>
<%end%>
<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<h1> Account </h1>

<p>
  <strong>Name:</strong>
  <%= @account.name %>
</p>


<p>
  <strong>Balance:</strong>
  <%= @account.balance %>
</p>

<p>
  <strong>Account Number:</strong>
  <%= @account.account_number %>
</p>

<p>
  <strong>Type of Account:</strong>
  <%= @account.account_type%>
</p>

<%= link_to 'Edit', edit_account_path(@account)%>
<%= link_to 'See All Accounts', accounts_path %>

<h2>Transactions</h2>

<% if @transactions.present? %>
  <table class="table table-striped mt-4">
    <thead>
      <tr>
        <th>Type</th>
        <th>Amount</th>
        <th>Source Account</th>
        <th>Destination Account</th>
        <th>Category</th>
        <th>Description</th>
        <th>Location</th>
        <th>Date</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @transactions.each do |transaction| %>
        <tr>
          <td><%= transaction.type.demodulize %></td>
          <td><%= transaction.amount %></td>
           <td>
            <% if transaction.is_a?(Transactions::Expense) || transaction.is_a?(Transactions::Transfer) %>
              <%= transaction.source_account&.name || "Null" %>
            <% else %>
              <%= '-' %>
            <% end %>
          </td>
          <td>
            <% if transaction.is_a?(Transactions::Income) || transaction.is_a?(Transactions::Transfer) %>
              <%= transaction.destination_account&.name || "Null" %>
            <% else %>
              <%= '-' %>
            <% end %>
          </td>
          <td>
             <%if transaction.is_a?(Transactions::Expense)%>
                <%= transaction.category.name %>
            <%else%> 
                <%= "-" %>
            <%end%>
          </td>
          <td><%= transaction.description %></td>
          <td><%= transaction.location %></td>
          <td><%= l(transaction.created_at, format: :short) %></td>
          <td>
            <%= link_to 'Show', transaction_path(transaction) %>
            <%= link_to 'Edit', edit_transaction_path(transaction) %>
            <%= button_to 'Delete', transaction_path(transaction), method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @transactions %>
<% else %>
  <p>No transactions available for this account.</p>
<% end %>